use agenda;

CREATE TABLE `Localidad`
(
  `Localidad` varchar(50) NOT NULL,
  PRIMARY KEY (`Localidad`)
);

INSERT INTO Localidad (Localidad) VALUES ('12 de Octubre');
INSERT INTO Localidad (Localidad) VALUES ('16 de Julio');
INSERT INTO Localidad (Localidad) VALUES ('17 de Agosto');
INSERT INTO Localidad (Localidad) VALUES ('25 de Mayo (Villa Veinticinco de Mayo)');
INSERT INTO Localidad (Localidad) VALUES ('30 de Agosto (Treinta de Agosto)');
INSERT INTO Localidad (Localidad) VALUES ('9 de Julio (Nueve de Julio)');
INSERT INTO Localidad (Localidad) VALUES ('Abbott');
INSERT INTO Localidad (Localidad) VALUES ('Acevedo');
INSERT INTO Localidad (Localidad) VALUES ('Adolfo Gonzales Chaves (Est. Chaves)');
INSERT INTO Localidad (Localidad) VALUES ('Agustina');
INSERT INTO Localidad (Localidad) VALUES ('Agustín Mosconi');
INSERT INTO Localidad (Localidad) VALUES ('Agustín Roca');
INSERT INTO Localidad (Localidad) VALUES ('Alberdi Viejo');
INSERT INTO Localidad (Localidad) VALUES ('Alberti (Est. Andrés Vaccarezza)');
INSERT INTO Localidad (Localidad) VALUES ('Alejandro Petión');
INSERT INTO Localidad (Localidad) VALUES ('Alfredo Demarchi (Est. Facundo Quiroga)');
INSERT INTO Localidad (Localidad) VALUES ('Almirante Brown (Adrogué)');
INSERT INTO Localidad (Localidad) VALUES ('Altamirano');
INSERT INTO Localidad (Localidad) VALUES ('Álvarez de Toledo');
INSERT INTO Localidad (Localidad) VALUES ('Alvarez Jonte');
INSERT INTO Localidad (Localidad) VALUES ('América');
INSERT INTO Localidad (Localidad) VALUES ('Andant');
INSERT INTO Localidad (Localidad) VALUES ('Antonio Carboni');
INSERT INTO Localidad (Localidad) VALUES ('Aparicio');
INSERT INTO Localidad (Localidad) VALUES ('Arboledas');
INSERT INTO Localidad (Localidad) VALUES ('Arenas Verdes');
INSERT INTO Localidad (Localidad) VALUES ('Arenaza');
INSERT INTO Localidad (Localidad) VALUES ('Argerich');
INSERT INTO Localidad (Localidad) VALUES ('Ariel');
INSERT INTO Localidad (Localidad) VALUES ('Arrecifes');
INSERT INTO Localidad (Localidad) VALUES ('Arribeños');
INSERT INTO Localidad (Localidad) VALUES ('Arroyo Corto');
INSERT INTO Localidad (Localidad) VALUES ('Arroyo de la Cruz');
INSERT INTO Localidad (Localidad) VALUES ('Arroyo Dulce');
INSERT INTO Localidad (Localidad) VALUES ('Arroyo Venado');
INSERT INTO Localidad (Localidad) VALUES ('Asamblea');
INSERT INTO Localidad (Localidad) VALUES ('Ascensión');
INSERT INTO Localidad (Localidad) VALUES ('Atalaya');
INSERT INTO Localidad (Localidad) VALUES ('Avellaneda');
INSERT INTO Localidad (Localidad) VALUES ('Ayacucho');
INSERT INTO Localidad (Localidad) VALUES ('Azcuénaga');
INSERT INTO Localidad (Localidad) VALUES ('Azopardo');
INSERT INTO Localidad (Localidad) VALUES ('Azul');
INSERT INTO Localidad (Localidad) VALUES ('Bahía Blanca');
INSERT INTO Localidad (Localidad) VALUES ('Bahía San Blas');
INSERT INTO Localidad (Localidad) VALUES ('Baigorrita');
INSERT INTO Localidad (Localidad) VALUES ('Bajo Hondo');
INSERT INTO Localidad (Localidad) VALUES ('Balcarce');
INSERT INTO Localidad (Localidad) VALUES ('Balneario Laguna de Gómez');
INSERT INTO Localidad (Localidad) VALUES ('Balneario Orense');
INSERT INTO Localidad (Localidad) VALUES ('Balneario Pehuen-Có');
INSERT INTO Localidad (Localidad) VALUES ('Balneario San Cayetano');
INSERT INTO Localidad (Localidad) VALUES ('Balneario Sauce Grande');
INSERT INTO Localidad (Localidad) VALUES ('Banderaló');
INSERT INTO Localidad (Localidad) VALUES ('Baradero');
INSERT INTO Localidad (Localidad) VALUES ('Barker');
INSERT INTO Localidad (Localidad) VALUES ('Barrio El Boquerón');
INSERT INTO Localidad (Localidad) VALUES ('Barrio El Mirador');
INSERT INTO Localidad (Localidad) VALUES ('Barrio El Taladro');
INSERT INTO Localidad (Localidad) VALUES ('Barrio La Gloria');
INSERT INTO Localidad (Localidad) VALUES ('Barrio Las Golondrinas');
INSERT INTO Localidad (Localidad) VALUES ('Barrio Lomas Altas');
INSERT INTO Localidad (Localidad) VALUES ('Barrio Los Bosquecitos');
INSERT INTO Localidad (Localidad) VALUES ('Barrio Los Pioneros (Barrio Tavella)');
INSERT INTO Localidad (Localidad) VALUES ('Barrio Parque Las Acacias');
INSERT INTO Localidad (Localidad) VALUES ('Barrio Río Salado');
INSERT INTO Localidad (Localidad) VALUES ('Barrio Santa Paula');
INSERT INTO Localidad (Localidad) VALUES ('Barrio Santa Rosa');
INSERT INTO Localidad (Localidad) VALUES ('Batán');
INSERT INTO Localidad (Localidad) VALUES ('Bayauca');
INSERT INTO Localidad (Localidad) VALUES ('Bellocq');
INSERT INTO Localidad (Localidad) VALUES ('Benitez');
INSERT INTO Localidad (Localidad) VALUES ('Benito Juárez (Est. Juárez)');
INSERT INTO Localidad (Localidad) VALUES ('Berazategui');
INSERT INTO Localidad (Localidad) VALUES ('Berdier');
INSERT INTO Localidad (Localidad) VALUES ('Berisso');
INSERT INTO Localidad (Localidad) VALUES ('Bermúdez');
INSERT INTO Localidad (Localidad) VALUES ('Berutti');
INSERT INTO Localidad (Localidad) VALUES ('Blancagrande');
INSERT INTO Localidad (Localidad) VALUES ('Blaquier');
INSERT INTO Localidad (Localidad) VALUES ('Bocayuva');
INSERT INTO Localidad (Localidad) VALUES ('Bordenave');
INSERT INTO Localidad (Localidad) VALUES ('Bragado');
INSERT INTO Localidad (Localidad) VALUES ('Cabildo');
INSERT INTO Localidad (Localidad) VALUES ('Cacharí');
INSERT INTO Localidad (Localidad) VALUES ('Cadret');
INSERT INTO Localidad (Localidad) VALUES ('Campana');
INSERT INTO Localidad (Localidad) VALUES ('Campos de Roca');
INSERT INTO Localidad (Localidad) VALUES ('Cañada Seca');
INSERT INTO Localidad (Localidad) VALUES ('Cañuelas');
INSERT INTO Localidad (Localidad) VALUES ('Capilla del Señor (Est. Capilla)');
INSERT INTO Localidad (Localidad) VALUES ('Capitán Castro');
INSERT INTO Localidad (Localidad) VALUES ('Capitán Sarmiento');
INSERT INTO Localidad (Localidad) VALUES ('Cardenal Cagliero');
INSERT INTO Localidad (Localidad) VALUES ('Carhué');
INSERT INTO Localidad (Localidad) VALUES ('Carlos Beguerie');
INSERT INTO Localidad (Localidad) VALUES ('Carlos Casares');
INSERT INTO Localidad (Localidad) VALUES ('Carlos Keen');
INSERT INTO Localidad (Localidad) VALUES ('Carlos María Naón');
INSERT INTO Localidad (Localidad) VALUES ('Carlos Salas');
INSERT INTO Localidad (Localidad) VALUES ('Carlos Tejedor');
INSERT INTO Localidad (Localidad) VALUES ('Carmen de Areco');
INSERT INTO Localidad (Localidad) VALUES ('Carmen de Patagones');
INSERT INTO Localidad (Localidad) VALUES ('Casalins');
INSERT INTO Localidad (Localidad) VALUES ('Casbas');
INSERT INTO Localidad (Localidad) VALUES ('Cascadas');
INSERT INTO Localidad (Localidad) VALUES ('Castelli');
INSERT INTO Localidad (Localidad) VALUES ('Castilla');
INSERT INTO Localidad (Localidad) VALUES ('Cazón');
INSERT INTO Localidad (Localidad) VALUES ('Centinela del Mar');
INSERT INTO Localidad (Localidad) VALUES ('Centro Guerrero');
INSERT INTO Localidad (Localidad) VALUES ('Cerro de la Gloria');
INSERT INTO Localidad (Localidad) VALUES ('Chacabuco');
INSERT INTO Localidad (Localidad) VALUES ('Chacras del Río Luján');
INSERT INTO Localidad (Localidad) VALUES ('Chapadmalal');
INSERT INTO Localidad (Localidad) VALUES ('Chascomús');
INSERT INTO Localidad (Localidad) VALUES ('Chasicó');
INSERT INTO Localidad (Localidad) VALUES ('Chillar');
INSERT INTO Localidad (Localidad) VALUES ('Chivilcoy');
INSERT INTO Localidad (Localidad) VALUES ('Claraz');
INSERT INTO Localidad (Localidad) VALUES ('Claromecó');
INSERT INTO Localidad (Localidad) VALUES ('Club de Campo las Malvinas');
INSERT INTO Localidad (Localidad) VALUES ('Club de Campo Los Puentes');
INSERT INTO Localidad (Localidad) VALUES ('Colón');
INSERT INTO Localidad (Localidad) VALUES ('Colonia Mauricio');
INSERT INTO Localidad (Localidad) VALUES ('Colonia Nievas');
INSERT INTO Localidad (Localidad) VALUES ('Colonia San Adolfo');
INSERT INTO Localidad (Localidad) VALUES ('Colonia San Martín');
INSERT INTO Localidad (Localidad) VALUES ('Colonia San Miguel');
INSERT INTO Localidad (Localidad) VALUES ('Colonia San Miguel Arcángel');
INSERT INTO Localidad (Localidad) VALUES ('Colonia San Ricardo (Est. Iriarte)');
INSERT INTO Localidad (Localidad) VALUES ('Colonia Seré');
INSERT INTO Localidad (Localidad) VALUES ('Comandante Nicanor Otamendi');
INSERT INTO Localidad (Localidad) VALUES ('Comodoro Py');
INSERT INTO Localidad (Localidad) VALUES ('Conesa');
INSERT INTO Localidad (Localidad) VALUES ('Copetonas');
INSERT INTO Localidad (Localidad) VALUES ('Coronel Boerr');
INSERT INTO Localidad (Localidad) VALUES ('Coronel Brandsen');
INSERT INTO Localidad (Localidad) VALUES ('Coronel Charlone');
INSERT INTO Localidad (Localidad) VALUES ('Coronel Dorrego');
INSERT INTO Localidad (Localidad) VALUES ('Coronel Martínez de Hoz (Ap. Kilómetro 322)');
INSERT INTO Localidad (Localidad) VALUES ('Coronel Pringles (Est. Pringles)');
INSERT INTO Localidad (Localidad) VALUES ('Coronel Seguí');
INSERT INTO Localidad (Localidad) VALUES ('Coronel Suárez');
INSERT INTO Localidad (Localidad) VALUES ('Coronel Vidal');
INSERT INTO Localidad (Localidad) VALUES ('Country Club El Casco');
INSERT INTO Localidad (Localidad) VALUES ('Country Club El Rodeo');
INSERT INTO Localidad (Localidad) VALUES ('Country Los Medanos');
INSERT INTO Localidad (Localidad) VALUES ('Crotto');
INSERT INTO Localidad (Localidad) VALUES ('Culullú');
INSERT INTO Localidad (Localidad) VALUES ('Cura Malal');
INSERT INTO Localidad (Localidad) VALUES ('Curarú');
INSERT INTO Localidad (Localidad) VALUES ('Daireaux');
INSERT INTO Localidad (Localidad) VALUES ('Darregueira');
INSERT INTO Localidad (Localidad) VALUES ('De Bary');
INSERT INTO Localidad (Localidad) VALUES ('De la Canal');
INSERT INTO Localidad (Localidad) VALUES ('De la Garma');
INSERT INTO Localidad (Localidad) VALUES ('Del Carril');
INSERT INTO Localidad (Localidad) VALUES ('Delfín Huergo');
INSERT INTO Localidad (Localidad) VALUES ('Del Valle');
INSERT INTO Localidad (Localidad) VALUES ('Diego Gaynor');
INSERT INTO Localidad (Localidad) VALUES ('Dolores');
INSERT INTO Localidad (Localidad) VALUES ('DOrbigny');
INSERT INTO Localidad (Localidad) VALUES ('Dudignac');
INSERT INTO Localidad (Localidad) VALUES ('Dufaur');
INSERT INTO Localidad (Localidad) VALUES ('Duggan');
INSERT INTO Localidad (Localidad) VALUES ('El Divisorio');
INSERT INTO Localidad (Localidad) VALUES ('El Dorado');
INSERT INTO Localidad (Localidad) VALUES ('El Marquesado');
INSERT INTO Localidad (Localidad) VALUES ('El Paraíso');
INSERT INTO Localidad (Localidad) VALUES ('El Pensamiento');
INSERT INTO Localidad (Localidad) VALUES ('El Perdido (Est. José A. Guisasola)');
INSERT INTO Localidad (Localidad) VALUES ('El Trigo');
INSERT INTO Localidad (Localidad) VALUES ('El Triunfo');
INSERT INTO Localidad (Localidad) VALUES ('Elvira');
INSERT INTO Localidad (Localidad) VALUES ('Emilio Ayarza');
INSERT INTO Localidad (Localidad) VALUES ('Emilio V. Bunge');
INSERT INTO Localidad (Localidad) VALUES ('Energia');
INSERT INTO Localidad (Localidad) VALUES ('Ensenada');
INSERT INTO Localidad (Localidad) VALUES ('Erézcano');
INSERT INTO Localidad (Localidad) VALUES ('Ernestina');
INSERT INTO Localidad (Localidad) VALUES ('Escalada');
INSERT INTO Localidad (Localidad) VALUES ('Escobar (Belén de Escobar)');
INSERT INTO Localidad (Localidad) VALUES ('Espartillar');
INSERT INTO Localidad (Localidad) VALUES ('Espigas');
INSERT INTO Localidad (Localidad) VALUES ('Estación Arenales');
INSERT INTO Localidad (Localidad) VALUES ('Estación Chapadmalal');
INSERT INTO Localidad (Localidad) VALUES ('Esteban Agustín Gascón');
INSERT INTO Localidad (Localidad) VALUES ('Esteban Echeverría (Monte Grande)');
INSERT INTO Localidad (Localidad) VALUES ('Estela');
INSERT INTO Localidad (Localidad) VALUES ('Ezeiza');
INSERT INTO Localidad (Localidad) VALUES ('Faro');
INSERT INTO Localidad (Localidad) VALUES ('Felipe Solá');
INSERT INTO Localidad (Localidad) VALUES ('Ferré');
INSERT INTO Localidad (Localidad) VALUES ('Florencio Varela');
INSERT INTO Localidad (Localidad) VALUES ('Florentino Ameghino');
INSERT INTO Localidad (Localidad) VALUES ('Fontezuela');
INSERT INTO Localidad (Localidad) VALUES ('Fortín Acha');
INSERT INTO Localidad (Localidad) VALUES ('Fortín Olavarría');
INSERT INTO Localidad (Localidad) VALUES ('Fortín Tiburcio');
INSERT INTO Localidad (Localidad) VALUES ('Francisco Madero');
INSERT INTO Localidad (Localidad) VALUES ('Franklin');
INSERT INTO Localidad (Localidad) VALUES ('Gahan');
INSERT INTO Localidad (Localidad) VALUES ('Gardey');
INSERT INTO Localidad (Localidad) VALUES ('Garré');
INSERT INTO Localidad (Localidad) VALUES ('General Alvear');
INSERT INTO Localidad (Localidad) VALUES ('General Arenales');
INSERT INTO Localidad (Localidad) VALUES ('General Belgrano');
INSERT INTO Localidad (Localidad) VALUES ('General Conesa');
INSERT INTO Localidad (Localidad) VALUES ('General Daniel Cerri (Est. General Cerri)');
INSERT INTO Localidad (Localidad) VALUES ('General Guido');
INSERT INTO Localidad (Localidad) VALUES ('General Hornos');
INSERT INTO Localidad (Localidad) VALUES ('General Juan Madariaga');
INSERT INTO Localidad (Localidad) VALUES ('General La Madrid');
INSERT INTO Localidad (Localidad) VALUES ('General Las Heras (Est. Las Heras)');
INSERT INTO Localidad (Localidad) VALUES ('General Lavalle');
INSERT INTO Localidad (Localidad) VALUES ('General Mansilla (Est. Bartolomé Bavio)');
INSERT INTO Localidad (Localidad) VALUES ('General OBrien');
INSERT INTO Localidad (Localidad) VALUES ('General Pinto');
INSERT INTO Localidad (Localidad) VALUES ('General Pirán');
INSERT INTO Localidad (Localidad) VALUES ('General Rivas');
INSERT INTO Localidad (Localidad) VALUES ('General Rodríguez');
INSERT INTO Localidad (Localidad) VALUES ('General Rojo');
INSERT INTO Localidad (Localidad) VALUES ('General San Martín');
INSERT INTO Localidad (Localidad) VALUES ('General Villegas (Est. Villegas)');
INSERT INTO Localidad (Localidad) VALUES ('Germania (Est. Mayor José Orellano)');
INSERT INTO Localidad (Localidad) VALUES ('Girodias');
INSERT INTO Localidad (Localidad) VALUES ('Gobernador Castro');
INSERT INTO Localidad (Localidad) VALUES ('Gobernador Udaondo');
INSERT INTO Localidad (Localidad) VALUES ('Gobernador Ugarte');
INSERT INTO Localidad (Localidad) VALUES ('Goldney');
INSERT INTO Localidad (Localidad) VALUES ('Gómez');
INSERT INTO Localidad (Localidad) VALUES ('González Moreno');
INSERT INTO Localidad (Localidad) VALUES ('Gorchs');
INSERT INTO Localidad (Localidad) VALUES ('Gorostiaga');
INSERT INTO Localidad (Localidad) VALUES ('Gowland');
INSERT INTO Localidad (Localidad) VALUES ('Goyena');
INSERT INTO Localidad (Localidad) VALUES ('Guaminí');
INSERT INTO Localidad (Localidad) VALUES ('Guerrico');
INSERT INTO Localidad (Localidad) VALUES ('Gunther');
INSERT INTO Localidad (Localidad) VALUES ('Hale');
INSERT INTO Localidad (Localidad) VALUES ('Henderson');
INSERT INTO Localidad (Localidad) VALUES ('Herrera Vegas');
INSERT INTO Localidad (Localidad) VALUES ('Hilario Ascasubi');
INSERT INTO Localidad (Localidad) VALUES ('Hinojo');
INSERT INTO Localidad (Localidad) VALUES ('Hortensia');
INSERT INTO Localidad (Localidad) VALUES ('Huanguelén');
INSERT INTO Localidad (Localidad) VALUES ('Hurlingham');
INSERT INTO Localidad (Localidad) VALUES ('Ignacio Correas');
INSERT INTO Localidad (Localidad) VALUES ('Indio Rico');
INSERT INTO Localidad (Localidad) VALUES ('Inés Indart');
INSERT INTO Localidad (Localidad) VALUES ('Ingeniero Moneta');
INSERT INTO Localidad (Localidad) VALUES ('Ingeniero Thompson');
INSERT INTO Localidad (Localidad) VALUES ('Inocencio Sosa');
INSERT INTO Localidad (Localidad) VALUES ('Irala');
INSERT INTO Localidad (Localidad) VALUES ('Irene');
INSERT INTO Localidad (Localidad) VALUES ('Irineo Portela');
INSERT INTO Localidad (Localidad) VALUES ('Ituzaingó');
INSERT INTO Localidad (Localidad) VALUES ('Jeppener');
INSERT INTO Localidad (Localidad) VALUES ('Jorge Born (Tomás Jofré)');
INSERT INTO Localidad (Localidad) VALUES ('José B. Casas');
INSERT INTO Localidad (Localidad) VALUES ('José C. Paz');
INSERT INTO Localidad (Localidad) VALUES ('José Juan Almeyra');
INSERT INTO Localidad (Localidad) VALUES ('Juan A. de la Peña');
INSERT INTO Localidad (Localidad) VALUES ('Juan Anchorena (Est. Urquiza)');
INSERT INTO Localidad (Localidad) VALUES ('Juan A. Pradere');
INSERT INTO Localidad (Localidad) VALUES ('Juan Bautista Alberdi (Est. Alberdi)');
INSERT INTO Localidad (Localidad) VALUES ('Juan Cousté (Est. Algarrobo)');
INSERT INTO Localidad (Localidad) VALUES ('Juan E. Barra');
INSERT INTO Localidad (Localidad) VALUES ('Juan F. Ibarra');
INSERT INTO Localidad (Localidad) VALUES ('Juan José Paso');
INSERT INTO Localidad (Localidad) VALUES ('Juan Nepomuceno Fernández');
INSERT INTO Localidad (Localidad) VALUES ('Junín');
INSERT INTO Localidad (Localidad) VALUES ('La Angelita');
INSERT INTO Localidad (Localidad) VALUES ('La Armonía');
INSERT INTO Localidad (Localidad) VALUES ('La Aurora (Est. La Niña)');
INSERT INTO Localidad (Localidad) VALUES ('Labardén');
INSERT INTO Localidad (Localidad) VALUES ('La Beba');
INSERT INTO Localidad (Localidad) VALUES ('La Carreta');
INSERT INTO Localidad (Localidad) VALUES ('La Choza');
INSERT INTO Localidad (Localidad) VALUES ('La Colina');
INSERT INTO Localidad (Localidad) VALUES ('La Constancia');
INSERT INTO Localidad (Localidad) VALUES ('La Delfina');
INSERT INTO Localidad (Localidad) VALUES ('La Emilia');
INSERT INTO Localidad (Localidad) VALUES ('La Gruta (Villa Serrana)');
INSERT INTO Localidad (Localidad) VALUES ('Laguna Alsina (Est. Bonifacio)');
INSERT INTO Localidad (Localidad) VALUES ('Laguna de Lobos');
INSERT INTO Localidad (Localidad) VALUES ('Laguna Vitel');
INSERT INTO Localidad (Localidad) VALUES ('La Invencible');
INSERT INTO Localidad (Localidad) VALUES ('La Larga');
INSERT INTO Localidad (Localidad) VALUES ('La Limpia');
INSERT INTO Localidad (Localidad) VALUES ('La Luisa');
INSERT INTO Localidad (Localidad) VALUES ('La Matanza (San Justo)');
INSERT INTO Localidad (Localidad) VALUES ('Lanús');
INSERT INTO Localidad (Localidad) VALUES ('La Pala');
INSERT INTO Localidad (Localidad) VALUES ('Laplacette');
INSERT INTO Localidad (Localidad) VALUES ('La Plata');
INSERT INTO Localidad (Localidad) VALUES ('Laprida');
INSERT INTO Localidad (Localidad) VALUES ('La Rica');
INSERT INTO Localidad (Localidad) VALUES ('Lartigau');
INSERT INTO Localidad (Localidad) VALUES ('Las Armas');
INSERT INTO Localidad (Localidad) VALUES ('Las Bahamas');
INSERT INTO Localidad (Localidad) VALUES ('Las Carabelas');
INSERT INTO Localidad (Localidad) VALUES ('Las Encadenadas');
INSERT INTO Localidad (Localidad) VALUES ('Las Flores');
INSERT INTO Localidad (Localidad) VALUES ('Las Marianas');
INSERT INTO Localidad (Localidad) VALUES ('Las Martinetas');
INSERT INTO Localidad (Localidad) VALUES ('La Sofía');
INSERT INTO Localidad (Localidad) VALUES ('Las Toninas');
INSERT INTO Localidad (Localidad) VALUES ('Las Toscas');
INSERT INTO Localidad (Localidad) VALUES ('La Trinidad');
INSERT INTO Localidad (Localidad) VALUES ('La Violeta');
INSERT INTO Localidad (Localidad) VALUES ('Leandro N. Alem');
INSERT INTO Localidad (Localidad) VALUES ('Líbano');
INSERT INTO Localidad (Localidad) VALUES ('Licenciado Matienzo');
INSERT INTO Localidad (Localidad) VALUES ('Lima');
INSERT INTO Localidad (Localidad) VALUES ('Lincoln');
INSERT INTO Localidad (Localidad) VALUES ('Lobería');
INSERT INTO Localidad (Localidad) VALUES ('Lobos');
INSERT INTO Localidad (Localidad) VALUES ('Lomas de Copello');
INSERT INTO Localidad (Localidad) VALUES ('Lomas del Río Luján (Est. Río Luján)');
INSERT INTO Localidad (Localidad) VALUES ('Lomas de Zamora');
INSERT INTO Localidad (Localidad) VALUES ('Loma Verde');
INSERT INTO Localidad (Localidad) VALUES ('López');
INSERT INTO Localidad (Localidad) VALUES ('López Lecube');
INSERT INTO Localidad (Localidad) VALUES ('Los Ángeles');
INSERT INTO Localidad (Localidad) VALUES ('Los Cardales');
INSERT INTO Localidad (Localidad) VALUES ('Los Indios');
INSERT INTO Localidad (Localidad) VALUES ('Los Naranjos');
INSERT INTO Localidad (Localidad) VALUES ('Los Pinos');
INSERT INTO Localidad (Localidad) VALUES ('Los Toldos');
INSERT INTO Localidad (Localidad) VALUES ('Lucas Monteverde');
INSERT INTO Localidad (Localidad) VALUES ('Luján');
INSERT INTO Localidad (Localidad) VALUES ('Magdala');
INSERT INTO Localidad (Localidad) VALUES ('Magdalena');
INSERT INTO Localidad (Localidad) VALUES ('Maipú');
INSERT INTO Localidad (Localidad) VALUES ('Malvinas Argentinas (Los Polvorines)');
INSERT INTO Localidad (Localidad) VALUES ('Manuel B. Gonnet (Est. French)');
INSERT INTO Localidad (Localidad) VALUES ('Manuel J. Cobo (Est. Lezama)');
INSERT INTO Localidad (Localidad) VALUES ('Manuel Ocampo');
INSERT INTO Localidad (Localidad) VALUES ('Mar Azul');
INSERT INTO Localidad (Localidad) VALUES ('Marcelino Ugarte (Est. Dennehy)');
INSERT INTO Localidad (Localidad) VALUES ('Mar Chiquita');
INSERT INTO Localidad (Localidad) VALUES ('Marcos Paz');
INSERT INTO Localidad (Localidad) VALUES ('Mar de Ajó (- San Bernardo)');
INSERT INTO Localidad (Localidad) VALUES ('Mar de Cobo');
INSERT INTO Localidad (Localidad) VALUES ('Mar del Plata');
INSERT INTO Localidad (Localidad) VALUES ('Mar del Sur');
INSERT INTO Localidad (Localidad) VALUES ('María Ignacia (Est. Vela)');
INSERT INTO Localidad (Localidad) VALUES ('Mariano Benítez');
INSERT INTO Localidad (Localidad) VALUES ('Mariano H. Alfonzo (Est. San Patricio)');
INSERT INTO Localidad (Localidad) VALUES ('Marisol');
INSERT INTO Localidad (Localidad) VALUES ('Massey (Est. Elordi)');
INSERT INTO Localidad (Localidad) VALUES ('Mauricio Hirsch');
INSERT INTO Localidad (Localidad) VALUES ('Máximo Fernández (Est. Juan F. Salaberry)');
INSERT INTO Localidad (Localidad) VALUES ('Máximo Paz (- Barrio Belgrano)');
INSERT INTO Localidad (Localidad) VALUES ('Mayor Buratovich');
INSERT INTO Localidad (Localidad) VALUES ('Maza');
INSERT INTO Localidad (Localidad) VALUES ('Mechita');
INSERT INTO Localidad (Localidad) VALUES ('Mechita (Est. Mecha)');
INSERT INTO Localidad (Localidad) VALUES ('Mechongué');
INSERT INTO Localidad (Localidad) VALUES ('Médanos');
INSERT INTO Localidad (Localidad) VALUES ('Mercedes');
INSERT INTO Localidad (Localidad) VALUES ('Merlo');
INSERT INTO Localidad (Localidad) VALUES ('Micaela Cascallares (Est. Cascallares)');
INSERT INTO Localidad (Localidad) VALUES ('Miramar');
INSERT INTO Localidad (Localidad) VALUES ('Mira Pampa');
INSERT INTO Localidad (Localidad) VALUES ('Moctezuma');
INSERT INTO Localidad (Localidad) VALUES ('Mones Cazón');
INSERT INTO Localidad (Localidad) VALUES ('Monte Hermoso');
INSERT INTO Localidad (Localidad) VALUES ('Moquehuá');
INSERT INTO Localidad (Localidad) VALUES ('Morea');
INSERT INTO Localidad (Localidad) VALUES ('Moreno');
INSERT INTO Localidad (Localidad) VALUES ('Morón');
INSERT INTO Localidad (Localidad) VALUES ('Morse');
INSERT INTO Localidad (Localidad) VALUES ('Napaleofú');
INSERT INTO Localidad (Localidad) VALUES ('Navarro');
INSERT INTO Localidad (Localidad) VALUES ('Necochea (- Quequén)');
INSERT INTO Localidad (Localidad) VALUES ('Nicanor Olivera (Est. La Dulce)');
INSERT INTO Localidad (Localidad) VALUES ('Norberto de la Riestra');
INSERT INTO Localidad (Localidad) VALUES ('Norumbega');
INSERT INTO Localidad (Localidad) VALUES ('Nueva Plata');
INSERT INTO Localidad (Localidad) VALUES ('Obligado');
INSERT INTO Localidad (Localidad) VALUES ('Ochandío');
INSERT INTO Localidad (Localidad) VALUES ('OHiggins');
INSERT INTO Localidad (Localidad) VALUES ('Olascoaga');
INSERT INTO Localidad (Localidad) VALUES ('Olavarría');
INSERT INTO Localidad (Localidad) VALUES ('Oliden');
INSERT INTO Localidad (Localidad) VALUES ('Olivera');
INSERT INTO Localidad (Localidad) VALUES ('Ordoqui');
INSERT INTO Localidad (Localidad) VALUES ('Orense');
INSERT INTO Localidad (Localidad) VALUES ('Oriente');
INSERT INTO Localidad (Localidad) VALUES ('Pago Chico (Villa del Mar)');
INSERT INTO Localidad (Localidad) VALUES ('Parada Orlando');
INSERT INTO Localidad (Localidad) VALUES ('Parada Robles (- Pavón)');
INSERT INTO Localidad (Localidad) VALUES ('Paraje La Agraria');
INSERT INTO Localidad (Localidad) VALUES ('Paraje la Ruta');
INSERT INTO Localidad (Localidad) VALUES ('Pardo');
INSERT INTO Localidad (Localidad) VALUES ('Pasman');
INSERT INTO Localidad (Localidad) VALUES ('Pasteur');
INSERT INTO Localidad (Localidad) VALUES ('Patricios');
INSERT INTO Localidad (Localidad) VALUES ('Paula');
INSERT INTO Localidad (Localidad) VALUES ('Pavón');
INSERT INTO Localidad (Localidad) VALUES ('Pearson');
INSERT INTO Localidad (Localidad) VALUES ('Pedernales');
INSERT INTO Localidad (Localidad) VALUES ('Pedro Luro');
INSERT INTO Localidad (Localidad) VALUES ('Pehuajó');
INSERT INTO Localidad (Localidad) VALUES ('Pellegrini');
INSERT INTO Localidad (Localidad) VALUES ('Pérez Millán');
INSERT INTO Localidad (Localidad) VALUES ('Pergamino');
INSERT INTO Localidad (Localidad) VALUES ('Pichincha');
INSERT INTO Localidad (Localidad) VALUES ('Piedritas');
INSERT INTO Localidad (Localidad) VALUES ('Pieres');
INSERT INTO Localidad (Localidad) VALUES ('Pigüé');
INSERT INTO Localidad (Localidad) VALUES ('Pila');
INSERT INTO Localidad (Localidad) VALUES ('Pilar');
INSERT INTO Localidad (Localidad) VALUES ('Pinamar');
INSERT INTO Localidad (Localidad) VALUES ('Pinzón');
INSERT INTO Localidad (Localidad) VALUES ('Pipinas');
INSERT INTO Localidad (Localidad) VALUES ('Pirovano');
INSERT INTO Localidad (Localidad) VALUES ('Pla');
INSERT INTO Localidad (Localidad) VALUES ('Plomer');
INSERT INTO Localidad (Localidad) VALUES ('Polvaredas');
INSERT INTO Localidad (Localidad) VALUES ('Pontaut');
INSERT INTO Localidad (Localidad) VALUES ('Porvenir');
INSERT INTO Localidad (Localidad) VALUES ('Posada de Los Lagos');
INSERT INTO Localidad (Localidad) VALUES ('Presidente Perón (Guernica)');
INSERT INTO Localidad (Localidad) VALUES ('Puan');
INSERT INTO Localidad (Localidad) VALUES ('Pueblo Doyle');
INSERT INTO Localidad (Localidad) VALUES ('Pueblo Gouin');
INSERT INTO Localidad (Localidad) VALUES ('Pueblo Nuevo');
INSERT INTO Localidad (Localidad) VALUES ('Pueblo San Jorge');
INSERT INTO Localidad (Localidad) VALUES ('Punta Alta (Est. Almirante Solier)');
INSERT INTO Localidad (Localidad) VALUES ('Punta Indio');
INSERT INTO Localidad (Localidad) VALUES ('Quenumá');
INSERT INTO Localidad (Localidad) VALUES ('Quilmes');
INSERT INTO Localidad (Localidad) VALUES ('Rafael Obligado');
INSERT INTO Localidad (Localidad) VALUES ('Ramallo');
INSERT INTO Localidad (Localidad) VALUES ('Ramón Biaus');
INSERT INTO Localidad (Localidad) VALUES ('Ramón Santamarina');
INSERT INTO Localidad (Localidad) VALUES ('Ramos Otero');
INSERT INTO Localidad (Localidad) VALUES ('Rancagua');
INSERT INTO Localidad (Localidad) VALUES ('Ranchos');
INSERT INTO Localidad (Localidad) VALUES ('Rauch');
INSERT INTO Localidad (Localidad) VALUES ('Rawson');
INSERT INTO Localidad (Localidad) VALUES ('Recalde');
INSERT INTO Localidad (Localidad) VALUES ('Reta');
INSERT INTO Localidad (Localidad) VALUES ('Río Tala');
INSERT INTO Localidad (Localidad) VALUES ('Rivera');
INSERT INTO Localidad (Localidad) VALUES ('Roberto Cano');
INSERT INTO Localidad (Localidad) VALUES ('Roberto J. Payró');
INSERT INTO Localidad (Localidad) VALUES ('Roberts');
INSERT INTO Localidad (Localidad) VALUES ('Rojas');
INSERT INTO Localidad (Localidad) VALUES ('Roosevelt');
INSERT INTO Localidad (Localidad) VALUES ('Roque Pérez');
INSERT INTO Localidad (Localidad) VALUES ('Ruta Sol (incl. Barrio El Peligro)');
INSERT INTO Localidad (Localidad) VALUES ('Saavedra');
INSERT INTO Localidad (Localidad) VALUES ('Saforcada');
INSERT INTO Localidad (Localidad) VALUES ('Saladillo');
INSERT INTO Localidad (Localidad) VALUES ('Salazar');
INSERT INTO Localidad (Localidad) VALUES ('Saldungaray');
INSERT INTO Localidad (Localidad) VALUES ('Salliqueló');
INSERT INTO Localidad (Localidad) VALUES ('Salto');
INSERT INTO Localidad (Localidad) VALUES ('Salvador María');
INSERT INTO Localidad (Localidad) VALUES ('Samborombón');
INSERT INTO Localidad (Localidad) VALUES ('San Agustín');
INSERT INTO Localidad (Localidad) VALUES ('San Andrés de Giles');
INSERT INTO Localidad (Localidad) VALUES ('San Antonio de Areco');
INSERT INTO Localidad (Localidad) VALUES ('San Bernardo (Est. Guanaco)');
INSERT INTO Localidad (Localidad) VALUES ('San Carlos de Bolívar (Est. Bolívar)');
INSERT INTO Localidad (Localidad) VALUES ('San Cayetano');
INSERT INTO Localidad (Localidad) VALUES ('San Clemente del Tuyú');
INSERT INTO Localidad (Localidad) VALUES ('San Emilio');
INSERT INTO Localidad (Localidad) VALUES ('San Enrique');
INSERT INTO Localidad (Localidad) VALUES ('San Esteban (Chiclana)');
INSERT INTO Localidad (Localidad) VALUES ('San Fernando');
INSERT INTO Localidad (Localidad) VALUES ('San Francisco de Bellocq');
INSERT INTO Localidad (Localidad) VALUES ('San Germán');
INSERT INTO Localidad (Localidad) VALUES ('San Isidro');
INSERT INTO Localidad (Localidad) VALUES ('San José');
INSERT INTO Localidad (Localidad) VALUES ('San Manuel');
INSERT INTO Localidad (Localidad) VALUES ('San Mauricio');
INSERT INTO Localidad (Localidad) VALUES ('San Mayol');
INSERT INTO Localidad (Localidad) VALUES ('San Miguel');
INSERT INTO Localidad (Localidad) VALUES ('San Miguel del Monte (Est. Monte)');
INSERT INTO Localidad (Localidad) VALUES ('San Nicolás de los Arroyos');
INSERT INTO Localidad (Localidad) VALUES ('San Pedro');
INSERT INTO Localidad (Localidad) VALUES ('San Román');
INSERT INTO Localidad (Localidad) VALUES ('San Sebastián');
INSERT INTO Localidad (Localidad) VALUES ('Sansinena');
INSERT INTO Localidad (Localidad) VALUES ('Santa Clara del Mar');
INSERT INTO Localidad (Localidad) VALUES ('Santa Coloma');
INSERT INTO Localidad (Localidad) VALUES ('Santa Eleodora');
INSERT INTO Localidad (Localidad) VALUES ('Santa Lucía');
INSERT INTO Localidad (Localidad) VALUES ('Santa Luisa');
INSERT INTO Localidad (Localidad) VALUES ('Santa María');
INSERT INTO Localidad (Localidad) VALUES ('Santa Regina');
INSERT INTO Localidad (Localidad) VALUES ('Santa Rosa');
INSERT INTO Localidad (Localidad) VALUES ('Santa Teresita (- Mar del Tuyú)');
INSERT INTO Localidad (Localidad) VALUES ('Santa Trinidad');
INSERT INTO Localidad (Localidad) VALUES ('Santo Domingo');
INSERT INTO Localidad (Localidad) VALUES ('Santo Tomas');
INSERT INTO Localidad (Localidad) VALUES ('San Vicente');
INSERT INTO Localidad (Localidad) VALUES ('Sarasa');
INSERT INTO Localidad (Localidad) VALUES ('Sevigne');
INSERT INTO Localidad (Localidad) VALUES ('Sierra Chica');
INSERT INTO Localidad (Localidad) VALUES ('Sierra de la Ventana');
INSERT INTO Localidad (Localidad) VALUES ('Sierra de los Padres');
INSERT INTO Localidad (Localidad) VALUES ('Sierras Bayas');
INSERT INTO Localidad (Localidad) VALUES ('Smith');
INSERT INTO Localidad (Localidad) VALUES ('Solanet');
INSERT INTO Localidad (Localidad) VALUES ('Sol de Mayo');
INSERT INTO Localidad (Localidad) VALUES ('Solís');
INSERT INTO Localidad (Localidad) VALUES ('Stroeder');
INSERT INTO Localidad (Localidad) VALUES ('Suipacha');
INSERT INTO Localidad (Localidad) VALUES ('Sundblad');
INSERT INTO Localidad (Localidad) VALUES ('Tamangueyú');
INSERT INTO Localidad (Localidad) VALUES ('Tandil');
INSERT INTO Localidad (Localidad) VALUES ('Tapalqué');
INSERT INTO Localidad (Localidad) VALUES ('Tedín Uriburu');
INSERT INTO Localidad (Localidad) VALUES ('Teniente Origone');
INSERT INTO Localidad (Localidad) VALUES ('Tigre');
INSERT INTO Localidad (Localidad) VALUES ('Timote');
INSERT INTO Localidad (Localidad) VALUES ('Todd');
INSERT INTO Localidad (Localidad) VALUES ('Tornquist');
INSERT INTO Localidad (Localidad) VALUES ('Torres');
INSERT INTO Localidad (Localidad) VALUES ('Trenque Lauquen');
INSERT INTO Localidad (Localidad) VALUES ('Tres Algarrobos (Est. Cuenca)');
INSERT INTO Localidad (Localidad) VALUES ('Tres Arroyos');
INSERT INTO Localidad (Localidad) VALUES ('Tres de Febrero (Caseros)');
INSERT INTO Localidad (Localidad) VALUES ('Tres Lomas');
INSERT INTO Localidad (Localidad) VALUES ('Tres Picos');
INSERT INTO Localidad (Localidad) VALUES ('Tres Sargentos');
INSERT INTO Localidad (Localidad) VALUES ('Triunvirato');
INSERT INTO Localidad (Localidad) VALUES ('Trongé');
INSERT INTO Localidad (Localidad) VALUES ('Udaquiola');
INSERT INTO Localidad (Localidad) VALUES ('Urdampilleta');
INSERT INTO Localidad (Localidad) VALUES ('Uribelarrea');
INSERT INTO Localidad (Localidad) VALUES ('Valdés');
INSERT INTO Localidad (Localidad) VALUES ('Vásquez');
INSERT INTO Localidad (Localidad) VALUES ('Vedia');
INSERT INTO Localidad (Localidad) VALUES ('Velloso');
INSERT INTO Localidad (Localidad) VALUES ('Verónica');
INSERT INTO Localidad (Localidad) VALUES ('Vicente Casares');
INSERT INTO Localidad (Localidad) VALUES ('Vicente López (Olivos)');
INSERT INTO Localidad (Localidad) VALUES ('Vieytes');
INSERT INTO Localidad (Localidad) VALUES ('Villa Alfredo Fortabat (Loma Negra)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Alsina (Est. Alsina)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Angélica (Est. El Socorro)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Cacique (Est. Alfredo Fortabat)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Castelar (Est. Erize)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Esperanza');
INSERT INTO Localidad (Localidad) VALUES ('Villa Espil');
INSERT INTO Localidad (Localidad) VALUES ('Villa Fournier (Est. 9 de Julio Sud)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Francia (Est. Coronel Granada)');
INSERT INTO Localidad (Localidad) VALUES ('Villa General Arias (Est. Kilómetro 638)');
INSERT INTO Localidad (Localidad) VALUES ('Villa General Savio (Est. Sánchez)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Gesell');
INSERT INTO Localidad (Localidad) VALUES ('Villa Grisolía (Est. Achupallas)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Iris');
INSERT INTO Localidad (Localidad) VALUES ('Villa La Arcadia');
INSERT INTO Localidad (Localidad) VALUES ('Villa Laguna La Brava');
INSERT INTO Localidad (Localidad) VALUES ('Villa La Serranía');
INSERT INTO Localidad (Localidad) VALUES ('Villa Lía');
INSERT INTO Localidad (Localidad) VALUES ('Villalonga');
INSERT INTO Localidad (Localidad) VALUES ('Villa Lynch Pueyrredón');
INSERT INTO Localidad (Localidad) VALUES ('Villa Manuel Pomar (El Arbolito)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Manuel Pomar');
INSERT INTO Localidad (Localidad) VALUES ('Villa María');
INSERT INTO Localidad (Localidad) VALUES ('Villa Moll (Est. Moll)');
INSERT INTO Localidad (Localidad) VALUES ('Villanueva (Ap. Río Salado)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Ortiz (Est. Coronel Mom)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Parque Girado');
INSERT INTO Localidad (Localidad) VALUES ('Villa Ramallo');
INSERT INTO Localidad (Localidad) VALUES ('Villa Rodríguez (Est. Barrow)');
INSERT INTO Localidad (Localidad) VALUES ('Villa Roth (Est. Ingeniero Balbín)');
INSERT INTO Localidad (Localidad) VALUES ('Villars');
INSERT INTO Localidad (Localidad) VALUES ('Villa Ruiz');
INSERT INTO Localidad (Localidad) VALUES ('Villa Saboya');
INSERT INTO Localidad (Localidad) VALUES ('Villa San José');
INSERT INTO Localidad (Localidad) VALUES ('Villa Sauze');
INSERT INTO Localidad (Localidad) VALUES ('Villa Ventana');
INSERT INTO Localidad (Localidad) VALUES ('Viña');
INSERT INTO Localidad (Localidad) VALUES ('Vivoratá');
INSERT INTO Localidad (Localidad) VALUES ('Warnes');
INSERT INTO Localidad (Localidad) VALUES ('Yutuyaco');
INSERT INTO Localidad (Localidad) VALUES ('Zárate');
INSERT INTO Localidad (Localidad) VALUES ('Zavalía');
INSERT INTO Localidad (Localidad) VALUES ('Zenón Videla Dorna');